### PR TITLE
Add optional to uuid

### PR DESCRIPTION
**Pull request by a-urth**
Make regexp to match empty string.

### CODE REVIEW

**Comment by sharpfun** [comment]
I would vote for extra parameter or uuidOptional, because sometimes id must be presented

**Comment by a-urth** [comment]
@sharpfun so it can be used with conjunction of `length_gt: 0` and it will make uuid mandatory. Its little bit confusing, but considering how its implemented I think its fine. And it seems that from our usage standpoint, validation for uuid is more important than for non empty string. And I really don't want to have two of the almost same fields. Adding extra keyword like `optional` also doesn't seem to be feasible because those rules are shared and changing/expanding lexis in general not something i would like to do with that project. So either I would go with extra check for length or ditch this solution at all.

**Comment by sharpfun** [comment]
@a-urth okay, that can help, can be applied where needed. Please change asterisk sign to question mark.

**Comment by yaronsumel** [comment]
I would go with `length_gt: 0 ` and not with this

**Pull request merged**
